version: '3.8'

services:
  db:
    image: mariadb:11.1
    container_name: cvven_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cvven
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
